### ISSUE TITLE
生学硬练章节有错别字

### ISSUE THREAD

**Issue by Tianliang3542** [xiaolai/1000-hours#4]
自我训练-生学硬练笑来老师，这个文字「听」，连起来是“挺”吧？

![screenshot-20240221-002659](https://github.com/xiaolai/1000-hours/assets/85776218/2e075b24-5e4b-46cb-8ee8-79abd4dd017c)

**Comment by xiaolai** [comment]
这个仓库合并到 [everyone-can-use-english](https://github.com/xiaolai/everyone-can-use-english) 里面去了。后继请在那边留言。
